### ISSUE TITLE
Add modulo operator

### ISSUE THREAD

**Issue by a-smith-github** [Cambridge-ICCS/ss23-git#3]
As requested by Jo Bloggs. Recommend using `%` as the operator, used across many languages.

Example:

    10 % 3 = 1

in RPN:

    3 10 % (-> stack would have 1 on top)

Likely add this code in calculator.py, [here](https://github.com/Cambridge-ICCS/ss23-git/blob/main/rpn-calc/src/calculator.py#L37).

**Comment by christopheredsall** [comment]
When the feature is documented we should say which method (Truncation/ Flooring/ Rounding/ ... ) we use

See:
-  https://en.wikipedia.org/wiki/Modulo#In_programming_languages
- :film_strip: [C++ Weekly - Ep 365 - Modulo (%): More Complicated Than You Think](https://www.youtube.com/watch?v=xVNYurap-lk)
